/*
 * Copyright 2021,2023-2024 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v9.0
processor: LPC55S36
package_id: LPC55S36JBD100
mcu_data: ksdk2_0
processor_version: 0.10.0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_iocon.h"
#include "pin_mux.h"
#include "fsl_gpio.h"
#include "sigbrd_application.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: cm33_core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '93', peripheral: FLEXCOMM0, signal: RXD_SDA_MOSI_DATA, pin_signal: PIO0_29/FC0_RXD_SDA_MOSI_DATA/CTIMER2_MAT3/SCT0_OUT8/TRACEDATA2/FC6_RXD_SDA_MOSI_DATA/CMP0_OUT/SECURE_GPIO0_29/PWM0_A1/SPI_DIN/EXTTRIG_IN3,
    mode: inactive, slew_rate: standard, invert: disabled, open_drain: disabled}
  - {pin_num: '95', peripheral: FLEXCOMM0, signal: TXD_SCL_MISO_WS, pin_signal: PIO0_30/FC0_TXD_SCL_MISO_WS/CTIMER0_MAT0/SCT0_OUT9/TRACEDATA1/CAN0_TD/FC6_TXD_SCL_MISO_WS/SECURE_GPIO0_30/PWM1_A1/AOI1_OUT0,
    mode: inactive, slew_rate: standard, invert: disabled, open_drain: disabled}
  - {pin_num: '37', peripheral: PWM1, signal: 'A, 0', pin_signal: PIO1_21/FC7_CTS_SDA_SSEL0/CTIMER3_MAT2/FC4_RXD_SDA_MOSI_DATA/PWM1_A0/TRIGOUT_1, mode: inactive,
    slew_rate: standard, invert: disabled, open_drain: disabled}
  - {pin_num: '49', peripheral: PWM1, signal: 'A, 1', pin_signal: PIO1_23/FC2_SCK/SCT0_OUT0/FC3_SSEL2/PWM1_A1/TRIGOUT_4/HSCMP2_IN1, mode: inactive, slew_rate: standard,
    invert: disabled, open_drain: disabled, asw0: disabled}
  - {pin_num: '77', peripheral: PWM1, signal: 'A, 2', pin_signal: PIO1_25/FC2_TXD_SCL_MISO_WS/SCT0_OUT2/UTICK_CAP0/PWM1_A2/SPI_SCLK/AOI0_OUT3, mode: inactive, slew_rate: standard,
    invert: disabled, open_drain: disabled}
  - {pin_num: '84', peripheral: PWM1, signal: 'B, 0', pin_signal: PIO0_3/FC3_RXD_SDA_MOSI_DATA/CTIMER0_MAT1/SCT0_OUT1/SCT_GPI3/FLEXSPI0_DATA2/SECURE_GPIO0_3/PWM1_B0,
    mode: inactive, slew_rate: standard, invert: disabled, open_drain: disabled}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M33 */
void BOARD_InitPins(void)
{
    /* Enables the clock for the I/O controller.: Enable Clock. */
    CLOCK_EnableClock(kCLOCK_Iocon);

    /* Enables the clock for the GPIO0 module */
    CLOCK_EnableClock(kCLOCK_Gpio0);

    /* Enables the clock for the GPIO1 module */
    CLOCK_EnableClock(kCLOCK_Gpio1);

    if(g_sigboardHWVer == EVSE_SIGBRD_1X)
    {
    	const uint32_t port0_pin10_config = (/* Pin is configured as ADC0_1A */
    			IOCON_PIO_FUNC0 |
				/* No addition pin function */
				IOCON_PIO_MODE_INACT |
				/* Standard mode, output slew rate control is enabled */
				IOCON_PIO_SLEW_STANDARD |
				/* Input function is not inverted */
				IOCON_PIO_INV_DI |
				/* Enables analog function */
				IOCON_PIO_ANALOG_EN |
				/* Open drain is disabled */
				IOCON_PIO_OPENDRAIN_DI |
				/* Analog switch 0 is closed (enabled) */
				IOCON_PIO_ASW0_EN);
    	/* PORT0 PIN10 (coords: 25) is configured as ADC0_1A */
    	IOCON_PinMuxSet(IOCON, 0U, 10U, port0_pin10_config);
    }

    else if(g_sigboardHWVer == EVSE_SIGBRD_2X)
    {
    	const uint32_t port0_pin15_config = (/* Pin is configured as ADC0_1A */
    			IOCON_PIO_FUNC0 |
				/* No addition pin function */
				IOCON_PIO_MODE_INACT |
				/* Standard mode, output slew rate control is enabled */
				IOCON_PIO_SLEW_STANDARD |
				/* Input function is not inverted */
				IOCON_PIO_INV_DI |
				/* Enables analog function */
				IOCON_PIO_ANALOG_EN |
				/* Open drain is disabled */
				IOCON_PIO_OPENDRAIN_DI |
				/* Analog switch 0 is closed (enabled) */
				IOCON_PIO_ASW0_EN);
    	/* PORT0 PIN15 (coords: 25) is configured as ADC0_3A */
    	IOCON_PinMuxSet(IOCON, 0U, 15U, port0_pin15_config);
    }

    const uint32_t port1_pin19_config = (/* Pin is configured as ADC0_4B */
        		IOCON_PIO_FUNC0 |
    			/* No addition pin function */
    			IOCON_PIO_MODE_INACT |
    			/* Standard mode, output slew rate control is enabled */
    			IOCON_PIO_SLEW_STANDARD |
    			/* Input function is not inverted */
    			IOCON_PIO_INV_DI |
    			/* Enables analog function */
    			IOCON_PIO_ANALOG_EN |
    			/* Open drain is disabled */
    			IOCON_PIO_OPENDRAIN_DI |
    			/* Analog switch 0 is closed (enabled) */
    			IOCON_PIO_ASW0_EN);
        /* PORT1 PIN19 (coords: 30) is configured as ADC0_4B */
    IOCON_PinMuxSet(IOCON, 1U, 19U, port1_pin19_config);

    const uint32_t port1_pin21_config_pwm = (/* Pin is configured as PWM1_A0 */
    		IOCON_PIO_FUNC11 |
			/* No addition pin function */
			IOCON_PIO_MODE_INACT |
			/* Standard mode, output slew rate control is enabled */
			IOCON_PIO_SLEW_STANDARD |
			/* Input function is not inverted */
			IOCON_PIO_INV_DI |
			/* Enables digital function */
			IOCON_PIO_DIGITAL_EN |
			/* Open drain is disabled */
			IOCON_PIO_OPENDRAIN_DI);
    /* PORT1 PIN21 (coords: 37) is configured as PWM1_A0 */
    IOCON_PinMuxSet(IOCON, 1U, 21U, port1_pin21_config_pwm);

    const uint32_t gpio_ip_config = (/* Pin is configured as PIO1_30 */
    		IOCON_PIO_FUNC0 |
			/* Selects pull-up function */
			IOCON_PIO_MODE_PULLUP |
			/* Standard mode, output slew rate control is enabled */
			IOCON_PIO_SLEW_STANDARD |
			/* Input function is not inverted */
			IOCON_PIO_INV_DI |
			/* Enables digital function */
			IOCON_PIO_DIGITAL_EN |
			/* Open drain is disabled */
			IOCON_PIO_OPENDRAIN_DI |
			/* Analog switch 0 is open (disabled) */
			IOCON_PIO_ASW0_DI);
    /* GFCI_INT: PORT1 PIN30 (coords: 65) is configured as PIO1_30 */
    IOCON_PinMuxSet(IOCON, 1U, 30U, gpio_ip_config);
    gpio_pin_config_t GFCI_config = {
    		.pinDirection = kGPIO_DigitalInput,
			.outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO1_30 (pin 65)  */
    GPIO_PinInit(GPIO, 1U, 30U, &GFCI_config);

    const uint32_t port0_pin1_config = (/* Pin is configured as CTIMER_INP0 */
    		IOCON_PIO_FUNC3 |
			/* No addition pin function */
			IOCON_PIO_MODE_INACT |
			/* Standard mode, output slew rate control is enabled */
			IOCON_PIO_SLEW_STANDARD |
			/* Input function is not inverted */
			IOCON_PIO_INV_DI |
			/* Enables digital function */
			IOCON_PIO_DIGITAL_EN |
			/* Open drain is disabled */
			IOCON_PIO_OPENDRAIN_DI);
    /* PORT0 PIN1 is configured as CTIMER_INP3 */
    IOCON_PinMuxSet(IOCON, 0U, 1U, port0_pin1_config);

#if 0
        gpio_pin_config_t HPGP_RESET_config = {
        		.pinDirection = kGPIO_DigitalOutput,
				.outputLogic = 1U
        };
        /* Initialize GPIO functionality on pin PIO0_13 (pin 70)  */
        GPIO_PinInit(GPIO, 0U, 13U, &HPGP_RESET_config);

        const uint32_t HPGP_RESET = (/* Pin is configured as PIO0_13 */
        		IOCON_PIO_FUNC0 |
				/* Selects pull-up function */
				//OCON_PIO_MODE_PULLUP |
				/* Standard mode, output slew rate control is enabled */
				IOCON_PIO_SLEW_STANDARD |
				/* Input function is not inverted */
				IOCON_PIO_INV_DI |
				/* Enables digital function */
				IOCON_PIO_DIGITAL_EN |
				/* Open drain is disabled */
				IOCON_PIO_OPENDRAIN_DI);
        /* PORT0 PIN13 (coords: 70) is configured as PIO0_13 */
        //IOCON_PinMuxSet(IOCON, 0U, 13U, HPGP_RESET);
#endif
        gpio_pin_config_t LED_config = {
        		.pinDirection = kGPIO_DigitalOutput,
				.outputLogic = 1U
        };
        /* Initialize GPIO functionality on pin PIO0_20 (pin 73)  */
        GPIO_PinInit(GPIO, 0U, 20U, &LED_config);
        /* Initialize GPIO functionality on pin PIO1_4 (pin 75)  */
        GPIO_PinInit(GPIO, 1U, 4U, &LED_config);

        const uint32_t LED = (/* Pin is configured as PIO0_20 */
        		IOCON_PIO_FUNC0 |
				/* Selects pull-up function */
				IOCON_PIO_MODE_PULLUP |
				/* Standard mode, output slew rate control is enabled */
				IOCON_PIO_SLEW_STANDARD |
				/* Input function is not inverted */
				IOCON_PIO_INV_DI |
				/* Enables digital function */
				IOCON_PIO_DIGITAL_EN |
				/* Open drain is disabled */
				IOCON_PIO_OPENDRAIN_DI);
        /* PORT0 PIN22 (coords: 73) is configured as PIO0_20 */
        IOCON_PinMuxSet(IOCON, 0U, 20U, LED);
        /* PORT1 PIN4 (coords: 75) is configured as PIO1_4 */
        IOCON_PinMuxSet(IOCON, 1U, 4U, LED);

        /* PILOT_SW */
        GPIO_PinInit(GPIO, 1U, 9U, &LED_config);
        /* PORT1 PIN9 (coords: 25) is configured as PIO1_9 */
        IOCON_PinMuxSet(IOCON, 1U, 9U, LED);

        const uint32_t port0_pin28_config = (/* Pin is configured as PIO0_28 */
        		IOCON_PIO_FUNC0 |
				/* Selects pull-up function */
				IOCON_PIO_MODE_PULLUP |
				/* Standard mode, output slew rate control is enabled */
				IOCON_PIO_SLEW_STANDARD |
				/* Input function is not inverted */
				IOCON_PIO_INV_DI |
				/* Enables digital function */
				IOCON_PIO_DIGITAL_EN |
				/* Open drain is disabled */
				IOCON_PIO_OPENDRAIN_DI |
				/* Analog switch 0 is open (disabled) */
				IOCON_PIO_ASW0_DI);
        /* GFCI_INT: PORT0 PIN28 (coords: 66) is configured as PIO0_28 */
        IOCON_PinMuxSet(IOCON, 0U, 28U, port0_pin28_config);
        gpio_pin_config_t WAKEUP_config = {
        		.pinDirection = kGPIO_DigitalInput,
				.outputLogic = 0U
        };
        /* Initialize GPIO functionality on pin PIO0_28 (pin 66)  */
        GPIO_PinInit(GPIO, 0U, 28U, &WAKEUP_config);

        const uint32_t RELAY = (/* Pin is configured as PIO1_24 */
        		IOCON_PIO_FUNC0 |
				/* Selects pull-up function */
				IOCON_PIO_MODE_PULLUP |
				/* Standard mode, output slew rate control is enabled */
				IOCON_PIO_SLEW_STANDARD |
				/* Input function is not inverted */
				IOCON_PIO_INV_DI |
				/* Enables digital function */
				IOCON_PIO_DIGITAL_EN |
				/* Open drain is disabled */
				IOCON_PIO_OPENDRAIN_DI);

        gpio_pin_config_t RELAY_ON_config = {
        		.pinDirection = kGPIO_DigitalOutput,
				.outputLogic = 1U
        };

        if(g_sigboardHWVer == EVSE_SIGBRD_1X)
        {

            /* PORT0 PIN22 (coords: 73) is configured as PIO0_20 */
            IOCON_PinMuxSet(IOCON, 1U, 28U, RELAY);

            /* Initialize GPIO functionality on pin PIO1_28 (pin 72)  */
            GPIO_PinInit(GPIO, 1U, 28U, &RELAY_ON_config);

        }

        else if(g_sigboardHWVer == EVSE_SIGBRD_2X)
        {
            /* PORT0 PIN22 (coords: 73) is configured as PIO0_20 */
            IOCON_PinMuxSet(IOCON, 1U, 29U, RELAY);

            /* Initialize GPIO functionality on pin PIO1_29 (pin 80)  */
            GPIO_PinInit(GPIO, 1U, 29U, &RELAY_ON_config);

        }

        /* PORT1 PIN4 (coords: 75) is configured as PIO1_4 */
        IOCON_PinMuxSet(IOCON, 0U, 24U, RELAY);

        gpio_pin_config_t RELAY_OFF_config = {
        		.pinDirection = kGPIO_DigitalOutput,
				.outputLogic = 0U
        };

        /* Initialize GPIO functionality on pin PIO0_24 (pin 69)  */
        GPIO_PinInit(GPIO, 0U, 24U, &RELAY_OFF_config);

        IOCON_PinMuxSet(IOCON, 0U, 14U, gpio_ip_config);
        gpio_pin_config_t EM_STOP_config = {
        		.pinDirection = kGPIO_DigitalInput,
				.outputLogic = 0U
        };
       /* Initialize GPIO functionality on pin PIO0_14 (pin 71)  */
        GPIO_PinInit(GPIO, 0U, 14U, &EM_STOP_config);

        const uint32_t port0_pin29_config = (/* Pin is configured as FC0_RXD_SDA_MOSI_DATA */
        		IOCON_PIO_FUNC1 |
				/* No addition pin function */
				IOCON_PIO_MODE_INACT |
				/* Standard mode, output slew rate control is enabled */
				IOCON_PIO_SLEW_STANDARD |
				/* Input function is not inverted */
				IOCON_PIO_INV_DI |
				/* Enables digital function */
				IOCON_PIO_DIGITAL_EN |
				/* Open drain is disabled */
				IOCON_PIO_OPENDRAIN_DI);
        /* PORT0 PIN29 (coords: 93) is configured as FC0_RXD_SDA_MOSI_DATA */
        IOCON_PinMuxSet(IOCON, 0U, 29U, port0_pin29_config);

#if 0
        const uint32_t port0_pin30_config = (/* Pin is configured as FC0_TXD_SCL_MISO_WS */
        		IOCON_PIO_FUNC1 |
				/* No addition pin function */
				IOCON_PIO_MODE_INACT |
				/* Standard mode, output slew rate control is enabled */
				IOCON_PIO_SLEW_STANDARD |
				/* Input function is not inverted */
				IOCON_PIO_INV_DI |
				/* Enables digital function */
				IOCON_PIO_DIGITAL_EN |
				/* Open drain is disabled */
				IOCON_PIO_OPENDRAIN_DI);
        /* PORT0 PIN30 (coords: 95) is configured as FC0_TXD_SCL_MISO_WS */
        IOCON_PinMuxSet(IOCON, 0U, 30U, port0_pin30_config);
#endif

        /* LIN */
        const uint32_t port0_pin2_config = (/* Pin is configured as FC3_TXD_SCL_MISO_WS */
        		IOCON_PIO_FUNC1 |
				/* No addition pin function */
				IOCON_PIO_MODE_INACT |
				/* Standard mode, output slew rate control is enabled */
				IOCON_PIO_SLEW_STANDARD |
				/* Input function is not inverted */
				IOCON_PIO_INV_DI |
				/* Enables digital function */
				IOCON_PIO_DIGITAL_EN |
				/* Open drain is disabled */
				IOCON_PIO_OPENDRAIN_DI);
        /* PORT0 PIN2 (coords: 81) is configured as FC3_TXD_SCL_MISO_WS */
        IOCON_PinMuxSet(IOCON, 0U, 2U, port0_pin2_config);

        const uint32_t port0_pin3_config = (/* Pin is configured as FC3_RXD_SDA_MOSI_DATA */
        		IOCON_PIO_FUNC1 |
				/* No addition pin function */
				IOCON_PIO_MODE_INACT |
				/* Standard mode, output slew rate control is enabled */
				IOCON_PIO_SLEW_STANDARD |
				/* Input function is not inverted */
				IOCON_PIO_INV_DI |
				/* Enables digital function */
				IOCON_PIO_DIGITAL_EN |
				/* Open drain is disabled */
				IOCON_PIO_OPENDRAIN_DI);
        /* PORT0 PIN3 (coords: 84) is configured as FC3_RXD_SDA_MOSI_DATA */
        IOCON_PinMuxSet(IOCON, 0U, 3U, port0_pin3_config);

        /* M_UART */
        const uint32_t port1_pin10_config = (/* Pin is configured as FC1_RXD */
        		IOCON_PIO_FUNC2 |
				/* No addition pin function */
				IOCON_PIO_MODE_INACT |
				/* Standard mode, output slew rate control is enabled */
				IOCON_PIO_SLEW_STANDARD |
				/* Input function is not inverted */
				IOCON_PIO_INV_DI |
				/* Enables digital function */
				IOCON_PIO_DIGITAL_EN |
				/* Open drain is disabled */
				IOCON_PIO_OPENDRAIN_DI);
        /* PORT1 PIN10 (coords: 39) is configured as FC1_RXD */
        IOCON_PinMuxSet(IOCON, 1U, 10U, port1_pin10_config);

        const uint32_t port1_pin11_config = (/* Pin is configured as FC1_TXD */
        		IOCON_PIO_FUNC2 |
				/* No addition pin function */
				IOCON_PIO_MODE_INACT |
				/* Standard mode, output slew rate control is enabled */
				IOCON_PIO_SLEW_STANDARD |
				/* Input function is not inverted */
				IOCON_PIO_INV_DI |
				/* Enables digital function */
				IOCON_PIO_DIGITAL_EN |
				/* Open drain is disabled */
				IOCON_PIO_OPENDRAIN_DI);
        /* PORT1 PIN11 (coords: 94) is configured as FC1_TXD */
        IOCON_PinMuxSet(IOCON, 1U, 11U, port1_pin11_config);

        const uint32_t port1_pin23_config = (/* Pin is configured as FC2_SCK */
        		IOCON_PIO_FUNC1 |
				/* Selects pull-up function */
				IOCON_PIO_MODE_PULLUP |
				/* Standard mode, output slew rate control is enabled */
				IOCON_PIO_SLEW_STANDARD |
				/* Input function is not inverted */
				IOCON_PIO_INV_DI |
				/* Enables digital function */
				IOCON_PIO_DIGITAL_EN |
				/* Open drain is disabled */
				IOCON_PIO_OPENDRAIN_DI |
				/* Analog switch 0 is open (disabled) */
				IOCON_PIO_ASW0_DI);
        /* PORT1 PIN23 (coords: 49) is configured as FC2_SCK */
        IOCON_PinMuxSet(IOCON, 1U, 23U, port1_pin23_config);

        const uint32_t port1_pin24_config = (/* Pin is configured as FC2_RXD_SDA_MOSI_DATA */
        		IOCON_PIO_FUNC1 |
				/* Selects pull-up function */
				IOCON_PIO_MODE_PULLUP |
				/* Standard mode, output slew rate control is enabled */
				IOCON_PIO_SLEW_STANDARD |
				/* Input function is not inverted */
				IOCON_PIO_INV_DI |
				/* Enables digital function */
				IOCON_PIO_DIGITAL_EN |
				/* Open drain is disabled */
				IOCON_PIO_OPENDRAIN_DI |
				/* Analog switch 0 is open (disabled) */
				IOCON_PIO_ASW0_DI);
        /* PORT1 PIN24 (coords: 3) is configured as FC2_RXD_SDA_MOSI_DATA */
        IOCON_PinMuxSet(IOCON, 1U, 24U, port1_pin24_config);

        const uint32_t port1_pin25_config = (/* Pin is configured as FC2_TXD_SCL_MISO_WS */
        		IOCON_PIO_FUNC1 |
				/* Selects pull-up function */
				IOCON_PIO_MODE_PULLUP |
				/* Standard mode, output slew rate control is enabled */
				IOCON_PIO_SLEW_STANDARD |
				/* Input function is not inverted */
				IOCON_PIO_INV_DI |
				/* Enables digital function */
				IOCON_PIO_DIGITAL_EN |
				/* Open drain is disabled */
				IOCON_PIO_OPENDRAIN_DI);
        /* PORT1 PIN25 (coords: 77) is configured as FC2_TXD_SCL_MISO_WS */
        IOCON_PinMuxSet(IOCON, 1U, 25U, port1_pin25_config);

        const uint32_t port1_pin26_config = (/* Pin is configured as FC2_CTS_SDA_SSEL0 */
        		IOCON_PIO_FUNC1 |
				/* Selects pull-up function */
				IOCON_PIO_MODE_PULLUP |
				/* Standard mode, output slew rate control is enabled */
				IOCON_PIO_SLEW_STANDARD |
				/* Input function is not inverted */
				IOCON_PIO_INV_DI |
				/* Enables digital function */
				IOCON_PIO_DIGITAL_EN |
				/* Open drain is disabled */
				IOCON_PIO_OPENDRAIN_DI);
        /* PORT1 PIN26 (coords: 68) is configured as FC2_CTS_SDA_SSEL0 */
        IOCON_PinMuxSet(IOCON, 1U, 26U, port1_pin26_config);

        const uint32_t port0_pin30_config = (/* Pin is configured as FC0_TXD_SCL_MISO_WS */
        		IOCON_PIO_FUNC1 |
				/* No addition pin function */
				IOCON_PIO_MODE_INACT |
				/* Standard mode, output slew rate control is enabled */
				IOCON_PIO_SLEW_STANDARD |
				/* Input function is not inverted */
				IOCON_PIO_INV_DI |
				/* Enables digital function */
				IOCON_PIO_DIGITAL_EN |
				/* Open drain is disabled */
				IOCON_PIO_OPENDRAIN_DI);
        /* PORT0 PIN30 (coords: 95) is configured as FC0_TXD_SCL_MISO_WS */
        IOCON_PinMuxSet(IOCON, 0U, 30U, port0_pin30_config);

}

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_PinStatus
 * Description   : Configures pin routing and optionally pin electrical features for getting the hardware version
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M33 */
uint8_t BOARD_PinStatus(void)
{
	uint8_t boardVer=0;
	uint8_t pin1_value, pin2_value, pin3_value = 0;

    /* Enables the clock for the I/O controller.: Enable Clock. */
    CLOCK_EnableClock(kCLOCK_Iocon);

    /* Enables the clock for the GPIO1 module */
    CLOCK_EnableClock(kCLOCK_Gpio1);


    const uint32_t gpio_ip_Config = (/* Pin is configured as PIO1_15,16,17 */
                                            IOCON_PIO_FUNC0 |
                                            /* No addition pin function */
											IOCON_PIO_MODE_PULLDOWN |
                                            /* Standard mode, output slew rate control is enabled */
                                            IOCON_PIO_SLEW_STANDARD |
                                            /* Input function is not inverted */
                                            IOCON_PIO_INV_DI |
                                            /* Enables digital function */
                                            IOCON_PIO_DIGITAL_EN |
                                            /* Open drain is disabled */
                                            IOCON_PIO_OPENDRAIN_DI);

    /* PORT1 PIN15, PIN16, PIN17 is configured as PULL_DOWN */
    IOCON_PinMuxSet(IOCON, 1U, 15U, gpio_ip_Config);
    IOCON_PinMuxSet(IOCON, 1U, 16U, gpio_ip_Config);
    IOCON_PinMuxSet(IOCON, 1U, 17U, gpio_ip_Config);

    gpio_pin_config_t BoardVer_config = {
    		.pinDirection = kGPIO_DigitalInput,
			.outputLogic = 0U
    };
    /* Initialize GPIO functionality */
    GPIO_PinInit(GPIO, 1U, 15U, &BoardVer_config);
    GPIO_PinInit(GPIO, 1U, 16U, &BoardVer_config);
    GPIO_PinInit(GPIO, 1U, 17U, &BoardVer_config);

    /*Read Pin Values*/
    pin1_value = (uint8_t) (GPIO_PinRead(GPIO, 1U, 15U));
    pin2_value = (uint8_t) (GPIO_PinRead(GPIO, 1U, 16U));
    pin3_value = (uint8_t) (GPIO_PinRead(GPIO, 1U, 17U));

    boardVer = (pin3_value << 2) | (pin2_value << 1) | pin1_value;

    return boardVer;

}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
